/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AddReviewMutation = {
    addReview: ({
        id: string;
    }) | null;
};
export type AddReviewMutationVariables = {
    id: string;
    commentBody: string;
};
